[package]
name = "security_scheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = { version = "2.0.0", features = ["test"] }
poem-openapi = "4.0.0"
tokio = "1.35.1"
